const fs = require('fs');
const fsPromises = require('fs/promises');
const path = require('path');

const store =
  require('../storage/memoryStore');

const {
  createFileMeta,
} = require('../models/FileMeta');

const {
  generateFileId,
  generateStorageFilename,
} =
  require('../utils/idGenerator');

const {
  MAX_FILE_SIZE,
  BLOCKED_FILE_EXTENSIONS,
  ALLOWED_FILE_EXTENSIONS,
} =
  require('../utils/constants');

const env =
  require('../config/env');

const STORAGE_DIR =
  path.resolve(
    env.FILE_STORAGE_PATH
  );

/*
 * Voice-message formats supported by the frontend
 * MediaRecorder implementation.
 *
 * These are added here so voice messages continue to
 * work even when the normal file allowlist does not
 * contain audio extensions.
 */
const ALLOWED_VOICE_EXTENSIONS = [
  '.webm',
  '.ogg',
  '.m4a',
];

function invalidFileError(
  message
) {
  const err =
    new Error(message);

  err.code =
    'INVALID_FILE_TYPE';

  return err;
}

function tooLargeError() {
  const err =
    new Error(
      'File is larger than the 20MB limit.'
    );

  err.code =
    'FILE_TOO_LARGE';

  return err;
}

/**
 * Sanitize only the display/original filename.
 *
 * The actual file on disk is NEVER named after this value.
 * Storage always uses generateStorageFilename().
 *
 * Windows separators must also be handled explicitly because
 * path.basename() on a Linux Render server does not treat
 * "\" as a path separator.
 */
function sanitizeOriginalName(
  name
) {
  return path
    .basename(
      String(
        name || 'file'
      )
    )
    .replace(
      /[/\\]/g,
      ''
    )
    .replace(
      /\.\./g,
      ''
    )
    .slice(0, 255);
}

function getExtension(
  filename
) {
  return path
    .extname(filename)
    .toLowerCase();
}

/**
 * Save encrypted ciphertext temporarily.
 */
async function saveEncryptedFile({
  roomId,
  buffer,
  iv,
  originalName,
  mimeType,
  declaredSize,
  expiresAt,
  uploaderSessionId,
}) {
  if (!Buffer.isBuffer(buffer)) {
    throw invalidFileError(
      'Invalid file data.'
    );
  }

  if (
    buffer.length >
    MAX_FILE_SIZE
  ) {
    throw tooLargeError();
  }

  /*
   * declaredSize is the ORIGINAL file size.
   *
   * The uploaded buffer is encrypted ciphertext and may
   * be slightly larger because of encryption overhead.
   *
   * Keep the existing 1KB tolerance.
   */
  if (
    Number.isFinite(
      declaredSize
    ) &&
    Math.abs(
      declaredSize -
        buffer.length
    ) > 1024
  ) {
    throw invalidFileError(
      'Declared file size does not match the uploaded data.'
    );
  }

  const safeName =
    sanitizeOriginalName(
      originalName ||
        'file'
    );

  const ext =
    getExtension(
      safeName
    );

  /*
   * Block dangerous extensions first.
   *
   * This remains enforced even for voice files.
   */
  if (
    BLOCKED_FILE_EXTENSIONS.includes(
      ext
    )
  ) {
    throw invalidFileError(
      'This file type isn’t allowed.'
    );
  }

  /*
   * Voice files are intentionally allowed even if the
   * general ALLOWED_FILE_EXTENSIONS list does not contain
   * audio formats.
   *
   * All other files must still pass the existing allowlist.
   */
  const isVoiceFile =
    ALLOWED_VOICE_EXTENSIONS.includes(
      ext
    );

  const isAllowedRegularFile =
    ALLOWED_FILE_EXTENSIONS.length
      ? ALLOWED_FILE_EXTENSIONS.includes(
          ext
        )
      : true;

  if (
    !isVoiceFile &&
    !isAllowedRegularFile
  ) {
    throw invalidFileError(
      'This file type isn’t allowed.'
    );
  }

  await fsPromises.mkdir(
    STORAGE_DIR,
    {
      recursive: true,
    }
  );

  const id =
    generateFileId();

  const storageFilename =
    generateStorageFilename();

  const filePath =
    path.join(
      STORAGE_DIR,
      storageFilename
    );

  /*
   * The storage filename is generated by the server.
   * User input can never control this path.
   */
  await fsPromises.writeFile(
    filePath,
    buffer
  );

  const record =
    createFileMeta({
      id,
      roomId,
      storageFilename,
      originalName:
        safeName,
      mimeType:
        mimeType ||
        'application/octet-stream',
      size:
        buffer.length,
      iv,
      uploaderSessionId,
      expiresAt,
    });

  store.addFile(
    record
  );

  return record;
}

/**
 * Return a stream for the encrypted file.
 */
async function getFileStream(
  fileId
) {
  const record =
    store.getFile(
      fileId
    );

  if (!record) {
    return null;
  }

  if (
    record.expiresAt &&
    new Date(
      record.expiresAt
    ).getTime() <=
      Date.now()
  ) {
    await deleteFileFromStorage(
      record
    );

    return null;
  }

  const filePath =
    path.join(
      STORAGE_DIR,
      record.storageFilename
    );

  try {
    await fsPromises.access(
      filePath
    );
  } catch {
    /*
     * The disk file disappeared, so remove the stale
     * metadata as well.
     */
    store.deleteFile(
      fileId
    );

    return null;
  }

  return {
    stream:
      fs.createReadStream(
        filePath
      ),
    meta:
      record,
  };
}

/**
 * Delete one file.
 *
 * Metadata is removed BEFORE awaiting disk deletion so
 * an expired/deleted file becomes unreachable immediately.
 */
async function deleteFile(
  fileId,
  requesterSessionId,
  isRoomOwner = false
) {
  const record =
    store.getFile(
      fileId
    );

  if (!record) {
    return false;
  }

  if (
    !isRoomOwner &&
    record.uploaderSessionId &&
    record.uploaderSessionId !==
      requesterSessionId
  ) {
    return false;
  }

  store.deleteFile(
    fileId
  );

  await unlinkQuietly(
    record.storageFilename
  );

  return true;
}

/**
 * Delete every file belonging to a room.
 *
 * File metadata is removed immediately. Disk cleanup then
 * runs asynchronously for all files.
 */
async function deleteRoomFiles(
  roomId
) {
  const roomFiles =
    store.getFilesByRoom(
      roomId
    );

  if (!roomFiles.length) {
    return;
  }

  /*
   * Immediately make every file unreachable.
   */
  roomFiles.forEach(
    (file) => {
      store.deleteFile(
        file.id
      );
    }
  );

  /*
   * Then remove the temporary ciphertext bytes.
   */
  await Promise.all(
    roomFiles.map(
      (file) =>
        unlinkQuietly(
          file.storageFilename
        )
    )
  );
}

/**
 * Internal file deletion helper.
 */
async function deleteFileFromStorage(
  record
) {
  store.deleteFile(
    record.id
  );

  await unlinkQuietly(
    record.storageFilename
  );
}

async function unlinkQuietly(
  storageFilename
) {
  if (!storageFilename) {
    return;
  }

  try {
    await fsPromises.unlink(
      path.join(
        STORAGE_DIR,
        storageFilename
      )
    );
  } catch {
    /*
     * The file is already gone.
     * That is the desired final state.
     */
  }
}

module.exports = {
  saveEncryptedFile,
  getFileStream,
  deleteFile,
  deleteRoomFiles,
};